version: '2.1'
services:
  rabbitmq:
    ports:
      - 5672:5672

  config:
    build: config
    ports:
      - 8888:8888

  registry:
    build: registry

  gateway:
    build: gateway

  auth-service:
    build: auth-service
    ports:
      - 5000:5000

  account-service:
    build: advert-service
    ports:
      - 6000:6000

  statistics-service:
    build: health-service
    ports:
      - 7000:7000

  notification-service:
    build: scanner-service
    ports:
      - 8000:8000

  monitoring:
    build: monitoring