security:
  oauth2:
    client:
      clientId: advert-service
      clientSecret: ${NOTIFICATION_SERVICE_PASSWORD}
      accessTokenUri: http://auth-service:5000/uaa/oauth/token
      grant-type: client_credentials
      scope: server

server:
  context-path: /api/advert
  port: 8000

spring:
  data:
    mongodb:
      host: advert-mongodb
      username: user
      password: ${MONGODB_PASSWORD}
      database: advert
      port: 27017