security:
  oauth2:
    client:
      clientId: health-service
      clientSecret: ${STATISTICS_SERVICE_PASSWORD}
      accessTokenUri: http://auth-service:5000/uaa/oauth/token
      grant-type: client_credentials
      scope: server

spring:
  data:
    mongodb:
      host: health-mongodb
      username: user
      password: ${MONGODB_PASSWORD}
      database: health
      port: 27017

server:
  context-path: /api/health
  port: 7000

rates:
  url: http://api.fixer.io